export * from './LoginPage/LoginPage.jsx';
export * from './RegisterPage/RegisterPage.jsx';
export * from './MainPage/MainPage.jsx';
export * from './WelcomePage/WelcomePage.jsx';
export * from './ProfilePage/ProfilePage.jsx';
export * from './ProjectsPage/ProjectsPage.jsx';
export * from './ProjectPage/ProjectPage.jsx';
export * from './TasksPage/TasksPage.jsx';
export * from './NotFoundPage/NotFoundPage.jsx';
